/patrol_node:
  ros__parameters:
    image_save_path: .
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      0.0, 0.0, 0.0,
      1.0, 2.0, 3.14,
      -4.5, 1.5, 1.57,
      -8.0, -5.0, 3.14 
    ]
    use_sim_time: false